name: hisma_flutter_example_app
description: Contains example applications for the hisma_flutter package.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hisma: ^0.3.1
  hisma_flutter: ^0.2.0+2
  hisma_visual_monitor: ^0.3.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
