name: hisma_flutter
description: Flutter navigation controlled by Hisma hierarchical state machines.
homepage: https://github.com/tamas-p/hisma
repository: https://github.com/tamas-p/hisma/tree/master/packages/hisma_flutter
version: 0.6.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hisma: ^0.6.0
  logging: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hisma_flutter_test: ^0.1.0
  hisma_visual_monitor: ^0.4.0+3
  integration_test:
    sdk: flutter
  lint: ^2.0.1
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
