name: hisma_console_monitor
description: Simple state machine monitor implementation that writes to the console for the Hisma package.
homepage: https://github.com/tamas-p/hisma
repository: https://github.com/tamas-p/hisma/tree/master/packages/hisma_console_monitor
version: 0.2.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  hisma: ^0.3.0+1
dev_dependencies:
  lint: ^2.0.1
  test: ^1.16.0
