name: hisma
description: Provides a declarative hierarchical state machine implementation that loosely follows the UML State Machine specification. 
homepage: https://github.com/tamas-p/hisma
repository: https://github.com/tamas-p/hisma/tree/master/packages/hisma
version: 0.1.1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  logging: ^1.1.0

dev_dependencies:
  hisma_console_monitor: ^0.1.1+1
  hisma_visual_monitor: ^0.1.1
  lint: ^1.7.2
  test: ^1.16.0
